services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP порт
      - "8025:8025"  # Web UI порт
    restart: unless-stopped

  file-server:
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/uploads:/usr/share/nginx/html/uploads
    command: >
      sh -c "
        mkdir -p /usr/share/nginx/html/uploads &&
        nginx -g 'daemon off;'
      "
    restart: unless-stopped
